#!/bin/bash

RUN_DIR=/var/vcap/sys/run/go-hello-world
LOG_DIR=/var/vcap/sys/log/go-hello-world
PIDFILE=${RUN_DIR}/pid
RUN_AS=vcap

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R $RUN_AS:$RUN_AS $RUN_DIR $LOG_DIR

    echo $$ > $PIDFILE

    cd /var/vcap/packages/main

    exec /var/vcap/packages/go-hello-world/main \
      >>  $LOG_DIR/web_ui.stdout.log \
      2>> $LOG_DIR/web_ui.stderr.log

    ;;

  stop)
    kill -9 `cat $PIDFILE`
    rm -f $PIDFILE

    ;;

  *)
    echo "Usage: ctl {start|stop}" ;;

esac`
